// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHAgjsxRMSmHO_O2CYtC8Uk9TPd11l_Aw',
    appId: '1:312697665843:web:8cd56ec73aa9f50f142646',
    messagingSenderId: '312697665843',
    projectId: 'simple-news-app-85541',
    authDomain: 'simple-news-app-85541.firebaseapp.com',
    storageBucket: 'simple-news-app-85541.appspot.com',
    measurementId: 'G-VF4SBSD59V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVRw6j5OD6DbWTCogpEOahOSxzXeXgkKw',
    appId: '1:312697665843:android:a1f3500adfcf53ee142646',
    messagingSenderId: '312697665843',
    projectId: 'simple-news-app-85541',
    storageBucket: 'simple-news-app-85541.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMhzrk1j4zDxLHliCWd83vDJIiFFHRHlQ',
    appId: '1:312697665843:ios:447a216585dca17c142646',
    messagingSenderId: '312697665843',
    projectId: 'simple-news-app-85541',
    storageBucket: 'simple-news-app-85541.appspot.com',
    iosClientId: '312697665843-c0r7ceehhlmhb5ji72l8jtfkor6ivadv.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleNewsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMhzrk1j4zDxLHliCWd83vDJIiFFHRHlQ',
    appId: '1:312697665843:ios:63468d7489217f4e142646',
    messagingSenderId: '312697665843',
    projectId: 'simple-news-app-85541',
    storageBucket: 'simple-news-app-85541.appspot.com',
    iosClientId: '312697665843-24dq0uq7vu6pjq5b85uab097smtvt9t1.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleNewsApp.RunnerTests',
  );
}
